name: Animated GitHub Contributions (Pacman AM / Snake PM)

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours (e.g., 12 AM & 12 PM UTC)
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run Pacman at 12 AM (00:00) UTC (AM)
      - name: Generate Pacman (AM)
        if: github.event.schedule == '0 */12 * * *' && (github.run_attempt == 1 && github.run_number % 2 == 1)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # Run Snake at 12 PM (12:00) UTC (PM)
      - name: Generate Snake (PM)
        if: github.event.schedule == '0 */12 * * *' && (github.run_attempt == 1 && github.run_number % 2 == 0)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-dark&snake=#ADD8E6&background=#000080

      # Deploy to output branch (works for both)
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}