name: Generate Pacman Animation

on:
  workflow_call:
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: output  # Checkout the output branch directly

      - name: Generate Pacman
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          output_file: latest-contribution.svg

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add latest-contribution.svg
          git commit -m "Update Pacman animation"
          git push
